name: babylandrajkot
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^2.3.1
  cloud_firestore: ^0.14.1+3
  cupertino_icons: ^1.0.0
  direct_select: ^1.1.0
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  firebase_storage: ^4.0.1
  flutter_boxicons: ^2.0.1
  flutter_html: ^1.0.2
  flutter_launcher_icons: ^0.8.1
  fluttertoast: ^7.1.6
  intl: ^0.16.1
  photo_view: ^0.10.2
  provider: ^4.3.2+2
  razorpay_flutter: ^1.2.2
  url_launcher: ^5.7.8
  woocommerce: ^0.9.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'assets/launcher_icon/babyland_icon.png'
  image_path_android: 'assets/launcher_icon/babyland_icon.png'
  image_path_ios: 'assets/launcher_icon/babyland_icon.png'

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
